### ISSUE TITLE
SQL queries: some queries have small inaccuracies 

### ISSUE THREAD

**Issue by luciamichielin** [carpentries-incubator/sql-humanities-lesson#5]
1) 
SELECT *
FROM catalogue
WHERE (year >= '1640') AND (status = 'Free');

should be 
SELECT *
FROM catalogue
WHERE (date >= '1640') AND (status = 'Free');

2)SELECT *
FROM catalogue
WHERE (year >= 1580) AND (author IN ('Aylett, Robert, 1583-1655?', 'Bacon, Francis, 1561-1626.'));

Should be
SELECT *
FROM catalogue
WHERE (date >= 1580) AND (author IN ('Aylett, Robert, 1583-1655?', 'Bacon, Francis, 1561-1626.'));

3) SELECT *
FROM cataloguue
ORDER BY Dates ASC;

should be 
SELECT *
FROM catalogue
ORDER BY date ASC;

4)SELECT *
FROM species
ORDER BY Dates DESC;

should be
SELECT *
FROM catalogue
ORDER BY date DESC;

5)SELECT *
FROM catalogue
ORDER BY Dates ASC, Author ASC;

should be
SELECT *
FROM catalogue
ORDER BY date ASC, author ASC;

**Comment by iaine** [comment]
Updated in above commit.
